#!/usr/bin/env python
from __future__ import print_function
from setuptools import setup


# Version
MAJOR = 0
MINOR = 3
MICRO = 1

gr1py_version = '{major}.{minor}.{micro}'.format(major=MAJOR, minor=MINOR, micro=MICRO)

with open('gr1py/_version.py', 'w') as f:
    f.write("""# Automatically generated by setup.py of gr1py. Do not edit.
version = '{version}'""".format(version=gr1py_version))

# Build parsing tables
try:
    import gr1py.form.gr1c
    import os.path
    assert os.path.exists('gr1py/form/parsetab.py'), 'Failed to build parsing table.'
except ImportError:
    print('!'*60)
    print('Please run again to cache the parsing table.')
    print('!'*60)

setup(version=gr1py_version)
