#!/usr/bin/env python
from setuptools import setup


# Version
MAJOR = 0
MINOR = 0
MICRO = 0

gr1py_version = '{major}.{minor}.{micro}'.format(major=MAJOR, minor=MINOR, micro=MICRO)

with open('gr1py/_version.py', 'w') as f:
    f.write("""# Automatically generated by setup.py of gr1py. Do not edit.
version = '{version}'""".format(version=gr1py_version))

# Build parsing tables
import gr1py.form.gr1c
import os.path
assert os.path.exists('gr1py/form/parsetab.py'), 'Failed to build parsing table.'


setup(name='gr1py',
      version=gr1py_version,
      author='Scott C. Livingston',
      author_email='slivingston@cds.caltech.edu',
      packages=['gr1py', 'gr1py.form'],
      package_data={'gr1py.form': ['parsetab.py']},
      install_requires=['ply', 'networkx'],
      entry_points={'console_scripts': ['gr1py = gr1py.cli:main']}
      )
